#!/bin/bash
# HZ-OneClick Bootstrapper v3.0
# Auto-generated by Horizon-Hybrid CI

# 1. Force Root
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: Please run as root (sudo -i)."
    exit 1
fi

INSTALL_DIR="/opt/hz-oneclick"
REPO_URL="[https://github.com/Hello-Pork-Belly/hz-oneclick.git](https://github.com/Hello-Pork-Belly/hz-oneclick.git)"

# 2. Ensure Git
if ! command -v git &> /dev/null; then
    echo "Installing Git..."
    if [ -f /etc/debian_version ]; then
        apt-get update -qq && apt-get install -y -qq git
    elif [ -f /etc/redhat-release ]; then
        yum install -y -q git
    fi
fi

# 3. Clone or Update
if [ -d "$INSTALL_DIR/.git" ]; then
    echo "Updating HZ-OneClick..."
    cd "$INSTALL_DIR" || exit 1
    git pull
else
    echo "Installing HZ-OneClick..."
    git clone "$REPO_URL" "$INSTALL_DIR"
fi

# 4. Launch Command Center
cd "$INSTALL_DIR" || exit 1
chmod +x lib/entry.sh
exec bash lib/entry.sh
